import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

import { QueryProviderWrapper } from "./wrapper/QueryProviderWrapper";
import { SessionCheckerWrapper } from "./wrapper/SessionCheckerWrapper";
import { GetUserWrapper } from "./wrapper/GetUserWrapper";

import Navbar from "./components/Navbar";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "ezyAuth",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <QueryProviderWrapper>
        <SessionCheckerWrapper>
          <GetUserWrapper>
            <body className={`${poppins.className} antialiased overflow-x-hidden md:flex items-center justify-start`}>
              <Navbar />
              {children}
            </body>
          </GetUserWrapper>
        </SessionCheckerWrapper>
      </QueryProviderWrapper>
    </html>
  );
}
